name: macos

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: macos-latest

    name: macos
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          cd linked-list
          make test

      - name: Test
        run: |
          cd linked-list
          make run_test
