name: macos

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: macos-latest

    name: macos
    steps:
      - uses: actions/checkout@v2

      - name: linked-list
        run: |
          cd linked-list
          make

      - name: heap
        run: |
          cd heap
          make

      - name: hash-map
        run: |
          cd hash-map
          make

      - name: stack
        run: |
          cd stack
          make
