name: ubuntu-amd64

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    name: ubuntu

    steps:
      - uses: actions/checkout@v2

      - name: Dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential

      - name: Build
        run: |
          cd linked-list
          make build_test

      - name: Test
        run: |
          cd linked-list
          make test
